### ISSUE TITLE
source for the 2.2.3 release

### ISSUE THREAD

**Issue by petabyteboy** [matrix-org/seshat#80]
**Describe the bug**
I can't find the source code of the 2.2.3 npm release in this repository. Can you please push the tag or point me in the right direction if it's somewhere else?

**To Reproduce**
1. Go to https://github.com/matrix-org/seshat
2. Click on "tags"
3. See how the 2.2.3 release tag is missing

**Expected behavior**
I would expect the source code of each release to be tagged and pushed to this repository.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/3250809/104975887-358d1080-59fc-11eb-849b-9194a18870e4.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I'm packaging an application that uses seshat and wanted to look at the source code of the seshat release it depends on.

**Comment by poljar** [comment]
Ah sorry, forgot to push the tag. Should be fixed now.
