### ISSUE TITLE
seshat 2.2.4 not published

### ISSUE THREAD

**Issue by twouters** [matrix-org/seshat#91]
Hi, it looks like version 2.2.4 is not available on yarnpkg: https://yarnpkg.com/package/matrix-seshat

**Comment by poljar** [comment]
The js bindings didn't change in 2.2.4, though yeah, let's publish a package since people won't know this.

**Comment by twouters** [comment]
I ran into https://github.com/matrix-org/seshat/issues/81 and attempted to update the dependency while building element-desktop when I noticed that the version isn't published.

**Comment by poljar** [comment]
It's a bit strange that it didn't pick up the latest Rust package for you, but I published the js now. Closing since this should be fixed.
